workflows:
  android-apk-build:
    name: Build Android APK
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
        ignore_failure: true
      - name: Build Debug APK
        script: |
          flutter build apk --debug
    artifacts:
      - build/**/outputs/**/*.apk
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - developer@specialone.com
        notify:
          success: true
          failure: true

  release-apk-build:
    name: Build Release APK
    max_build_duration: 60
    instance_type: linux_x2
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*'
          include: true
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
      - name: Build Release APK
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - admin@specialone.com
        notify:
          success: true
          failure: true

