workflows:
  android-build:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Analyze project
        script: |
          flutter analyze
      - name: Run tests (optional)
        script: |
          flutter test
        ignore_failure: true
      - name: Build APK (release)
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
